#!/usr/bin/env python3
"""Generate .devcontainer/ files for the calling repository.

Used by: .github/workflows/reusable-devcontainer.yml (step "Generate .devcontainer files")

Environment variables (set by the workflow):
  CONTAINER_NAME   Display name for the devcontainer (e.g. "Peds dev")
  CLAUDE_VERSION   @anthropic-ai/claude-code version to embed
  EXTRA_FEATURES   JSON object of additional devcontainer features to merge
  CENTRAL_DIR      Path to the checked-out ruralpeds/.github repo (for templates)

Outputs:
  .devcontainer/devcontainer.json
  .devcontainer/post-create.sh
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

# Minimum safe claude-code version (verified against GitHub Advisory DB).
MIN_CLAUDE_VERSION = "2.1.123"

# ── Devcontainer feature base set ────────────────────────────────────────────
BASE_FEATURES: dict[str, dict] = {
    "ghcr.io/devcontainers/features/node:1": {"version": "20", "nvmVersion": "latest"},
    "ghcr.io/devcontainers/features/python:1": {"version": "3.12", "installTools": True},
    "ghcr.io/devcontainers/features/go:1": {"version": "1.23"},
    "ghcr.io/devcontainers/features/rust:1": {"version": "stable", "profile": "default"},
    "ghcr.io/devcontainers/features/github-cli:1": {
        "installDirectlyFromGitHubRelease": True,
        "version": "latest",
    },
}

# VS Code extensions installed in every ruralpeds dev container.
BASE_EXTENSIONS: list[str] = [
    "ms-python.python",
    "ms-python.mypy-type-checker",
    "charliermarsh.ruff",
    "rust-lang.rust-analyzer",
    "julialang.language-julia",
    "golang.go",
    "esbenp.prettier-vscode",
    "dbaeumer.vscode-eslint",
    "github.vscode-github-actions",
    "redhat.vscode-yaml",
]


def _validate_version(version: str, minimum: str) -> None:
    """Raise SystemExit if version < minimum."""
    try:
        from packaging.version import Version  # type: ignore[import-untyped]
    except ImportError:
        # packaging not available — do a best-effort string comparison.
        if version < minimum:
            sys.exit(
                f"::error::claude-version {version!r} is below the minimum safe "
                f"version {minimum!r}."
            )
        return

    ver = Version(version)
    min_ver = Version(minimum)
    if ver < min_ver:
        print(
            f"::error::claude-version {ver} is below the minimum safe version {min_ver}.",
            file=sys.stderr,
        )
        print(
            "::error::Check GitHub Advisory Database for @anthropic-ai/claude-code CVEs.",
            file=sys.stderr,
        )
        sys.exit(1)


def _strip_json_comments(text: str) -> str:
    """Remove // line comments from JSON-with-comments (DevContainer format)."""
    # Remove // comments not inside strings — simple heuristic sufficient for
    # our controlled template files.
    return re.sub(r"(?m)^\s*//.*$", "", text)


def _load_template(central_dir: Path, filename: str) -> str:
    template_path = central_dir / "devcontainer-templates" / filename
    if not template_path.exists():
        sys.exit(f"::error::Template not found: {template_path}")
    return template_path.read_text(encoding="utf-8")


def _render_devcontainer_json(
    container_name: str,
    extra_features: dict,
    central_dir: Path,
) -> str:
    """Render devcontainer.json from the canonical template."""
    raw = _load_template(central_dir, "devcontainer.json")
    clean = _strip_json_comments(raw)
    config: dict = json.loads(clean)

    # Apply caller overrides.
    config["name"] = container_name

    # Merge extra features on top of the base set.
    merged_features = dict(BASE_FEATURES)
    merged_features.update(extra_features)
    config["features"] = merged_features

    # Ensure standard extensions are present (deduplicated, order preserved).
    existing_ext: list[str] = (
        config.get("customizations", {}).get("vscode", {}).get("extensions", [])
    )
    seen: set[str] = set(existing_ext)
    for ext in BASE_EXTENSIONS:
        if ext not in seen:
            existing_ext.append(ext)
            seen.add(ext)
    config.setdefault("customizations", {}).setdefault("vscode", {})["extensions"] = existing_ext

    # Preserve remoteEnv with ANTHROPIC_API_KEY forwarding.
    config.setdefault("remoteEnv", {}).setdefault(
        "ANTHROPIC_API_KEY", "${localEnv:ANTHROPIC_API_KEY}"
    )

    header = (
        "// ruralpeds org-standard dev container — generated by reusable-devcontainer.yml.\n"
        "// To opt this file out of future syncs, add: AUTO-SYNC-OPT-OUT anywhere here.\n"
    )
    return header + json.dumps(config, indent=2) + "\n"


def _render_post_create_sh(claude_version: str, central_dir: Path) -> str:
    """Render post-create.sh from the template, substituting the Claude version."""
    template = _load_template(central_dir, "post-create.sh")
    # Replace the pinned version line.
    rendered = re.sub(
        r'^(CLAUDE_CODE_VERSION=")[^"]*(")',
        rf'\g<1>{claude_version}\g<2>',
        template,
        flags=re.MULTILINE,
    )
    if f'CLAUDE_CODE_VERSION="{claude_version}"' not in rendered:
        sys.exit(
            "::error::Could not substitute CLAUDE_CODE_VERSION in post-create.sh template. "
            "Check that the template contains a line: CLAUDE_CODE_VERSION=\"<version>\""
        )
    return rendered


def main() -> int:
    container_name = os.environ.get("CONTAINER_NAME", "ruralpeds dev").strip()
    claude_version = os.environ.get("CLAUDE_VERSION", MIN_CLAUDE_VERSION).strip()
    extra_features_raw = os.environ.get("EXTRA_FEATURES", "{}").strip()
    central_dir = Path(os.environ.get("CENTRAL_DIR", ".")).resolve()

    # Validate inputs.
    _validate_version(claude_version, MIN_CLAUDE_VERSION)

    try:
        extra_features: dict = json.loads(extra_features_raw) if extra_features_raw else {}
    except json.JSONDecodeError as exc:
        print(f"::error::Invalid JSON in EXTRA_FEATURES: {exc}", file=sys.stderr)
        return 1

    if not isinstance(extra_features, dict):
        print("::error::EXTRA_FEATURES must be a JSON object ({...}).", file=sys.stderr)
        return 1

    # Render outputs.
    devcontainer_json = _render_devcontainer_json(container_name, extra_features, central_dir)
    post_create_sh = _render_post_create_sh(claude_version, central_dir)

    # Write .devcontainer/ directory.
    out_dir = Path(".devcontainer")
    out_dir.mkdir(exist_ok=True)

    (out_dir / "devcontainer.json").write_text(devcontainer_json, encoding="utf-8")
    post_create_path = out_dir / "post-create.sh"
    post_create_path.write_text(post_create_sh, encoding="utf-8")
    post_create_path.chmod(0o755)

    print(f"Written: {out_dir / 'devcontainer.json'}")
    print(f"Written: {post_create_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
