#!/usr/bin/env python3
"""Sync the org-standard .devcontainer/ config from the central ruralpeds/.github
repo to a target repository, then open a pull request.

Used by: .github/workflows/devcontainer-sweep.yml

Environment variables:
  CENTRAL_DIR    Absolute path to the checked-out ruralpeds/.github repo
  TARGET_DIR     Absolute path to the checked-out target repo
  TARGET_REPO    "owner/name" slug of the target (e.g. timothyhartzog/Peds)
  DRY_RUN        "true" to print diffs without opening PRs
  CLAUDE_VERSION @anthropic-ai/claude-code version to embed (default: 2.1.123)
  GH_TOKEN       Token with contents:write + pull-requests:write on TARGET_REPO

Opt-out: adding AUTO-SYNC-OPT-OUT anywhere inside a target file prevents that
specific file from being overwritten on subsequent runs.
"""

from __future__ import annotations

import datetime as dt
import json
import os
import re
import subprocess
import sys
from pathlib import Path

OPT_OUT_MARKER = "AUTO-SYNC-OPT-OUT"
MIN_CLAUDE_VERSION = "2.1.123"
DEFAULT_CLAUDE_VERSION = MIN_CLAUDE_VERSION


# ─────────────────────────────────────────────────────────────────────────────


def _run(
    args: list[str],
    cwd: Path | None = None,
    check: bool = True,
    capture: bool = True,
) -> subprocess.CompletedProcess:
    return subprocess.run(
        args,
        cwd=str(cwd) if cwd else None,
        capture_output=capture,
        text=True,
        check=check,
    )


def _has_opt_out(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        return OPT_OUT_MARKER in path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False


def _strip_json_comments(text: str) -> str:
    """Strip // line comments from JSON-with-comments."""
    return re.sub(r"(?m)^\s*//.*$", "", text)


def _validate_version(version: str, minimum: str) -> None:
    try:
        from packaging.version import Version  # type: ignore[import-untyped]
        if Version(version) < Version(minimum):
            sys.exit(
                f"::error::CLAUDE_VERSION {version!r} is below the minimum safe "
                f"version {minimum!r}."
            )
    except ImportError:
        if version < minimum:
            sys.exit(
                f"::error::CLAUDE_VERSION {version!r} appears below minimum {minimum!r}."
            )


def _render_post_create(template_text: str, claude_version: str) -> str:
    """Substitute CLAUDE_CODE_VERSION in the post-create.sh template."""
    rendered = re.sub(
        r'^(CLAUDE_CODE_VERSION=")[^"]*(")',
        rf'\g<1>{claude_version}\g<2>',
        template_text,
        flags=re.MULTILINE,
    )
    if f'CLAUDE_CODE_VERSION="{claude_version}"' not in rendered:
        sys.exit(
            "::error::Could not substitute CLAUDE_CODE_VERSION in post-create.sh. "
            "Template line must be: CLAUDE_CODE_VERSION=\"<version>\""
        )
    return rendered


def _render_devcontainer_json(template_text: str, container_name: str) -> str:
    """Parse the template JSON, set the container name, and re-serialise."""
    clean = _strip_json_comments(template_text)
    config: dict = json.loads(clean)
    config["name"] = container_name
    header = (
        "// ruralpeds org-standard dev container — generated by devcontainer-sweep.\n"
        "// To opt this file out of future syncs, add: AUTO-SYNC-OPT-OUT anywhere here.\n"
    )
    return header + json.dumps(config, indent=2) + "\n"


def _sync_file(src_text: str, dst: Path, dry_run: bool) -> tuple[bool, str]:
    """Write src_text to dst unless the file opts out or is identical.

    Returns (changed: bool, status_message: str).
    """
    if _has_opt_out(dst):
        return False, f"skip (opt-out): {dst.relative_to(dst.parent.parent)}"

    dst.parent.mkdir(parents=True, exist_ok=True)
    current = dst.read_text(encoding="utf-8", errors="replace") if dst.exists() else None

    if current == src_text:
        return False, f"unchanged: {dst.relative_to(dst.parent.parent)}"

    if dry_run:
        return True, f"WOULD UPDATE: {dst.relative_to(dst.parent.parent)}"

    dst.write_text(src_text, encoding="utf-8")
    # Ensure post-create.sh is executable.
    if dst.name == "post-create.sh":
        dst.chmod(0o755)
    return True, f"updated: {dst.relative_to(dst.parent.parent)}"


def main() -> int:
    central_dir = Path(os.environ["CENTRAL_DIR"]).resolve()
    target_dir = Path(os.environ["TARGET_DIR"]).resolve()
    target_repo = os.environ["TARGET_REPO"]
    dry_run = (os.environ.get("DRY_RUN", "false") or "false").lower() == "true"
    claude_version = os.environ.get("CLAUDE_VERSION", DEFAULT_CLAUDE_VERSION).strip()

    print(f"Syncing devcontainer into {target_repo}")
    print(f"  central:       {central_dir}")
    print(f"  target:        {target_dir}")
    print(f"  claude:        @anthropic-ai/claude-code@{claude_version}")
    print(f"  dry_run:       {dry_run}")
    print()

    _validate_version(claude_version, MIN_CLAUDE_VERSION)

    tpl_dir = central_dir / "devcontainer-templates"

    # Derive a readable container name from the repo slug (e.g. "Peds dev").
    repo_short = target_repo.split("/")[-1]
    container_name = f"{repo_short} dev"

    # Render devcontainer.json.
    dc_template = (tpl_dir / "devcontainer.json").read_text(encoding="utf-8")
    dc_rendered = _render_devcontainer_json(dc_template, container_name)

    # Render post-create.sh.
    pc_template = (tpl_dir / "post-create.sh").read_text(encoding="utf-8")
    pc_rendered = _render_post_create(pc_template, claude_version)

    files_to_sync: list[tuple[str, Path]] = [
        (dc_rendered, target_dir / ".devcontainer" / "devcontainer.json"),
        (pc_rendered, target_dir / ".devcontainer" / "post-create.sh"),
    ]

    changes: list[Path] = []
    for content, dst in files_to_sync:
        changed, msg = _sync_file(content, dst, dry_run)
        prefix = "  CHG " if changed else "  ok  "
        print(f"{prefix}{msg}")
        if changed:
            changes.append(dst.relative_to(target_dir))

    if not changes:
        print("\nNo changes to push.")
        return 0

    if dry_run:
        print(f"\nDry run: {len(changes)} file(s) would change.")
        return 0

    # ── Commit and push to a new branch ──────────────────────────────────────
    branch = f"chore/add-devcontainer-{dt.datetime.utcnow():%Y%m%d-%H%M%S}"

    _run(["git", "config", "user.name",  "github-actions[bot]"], cwd=target_dir)
    _run(
        ["git", "config", "user.email",
         "41898282+github-actions[bot]@users.noreply.github.com"],
        cwd=target_dir,
    )
    _run(["git", "checkout", "-b", branch], cwd=target_dir)

    change_paths = [str(p) for p in changes]
    _run(["git", "add"] + change_paths, cwd=target_dir)

    commit_msg = (
        "chore: add/update dev container with Claude Code embedded\n\n"
        f"Files updated ({len(changes)}):\n"
        + "\n".join(f"  - {p}" for p in change_paths)
        + "\n\n"
        f"Claude Code: @anthropic-ai/claude-code@{claude_version}\n"
        "Source: https://github.com/ruralpeds/.github/tree/main/devcontainer-templates/\n\n"
        "To opt a file out of future syncs, add the marker\n"
        "`AUTO-SYNC-OPT-OUT` anywhere in the file."
    )
    _run(["git", "commit", "-m", commit_msg], cwd=target_dir)
    _run(["git", "push", "origin", branch], cwd=target_dir)

    # ── Open PR via gh CLI ────────────────────────────────────────────────────
    pr_body = (
        "Automated sync from `ruralpeds/.github`.\n\n"
        "**Files updated:**\n"
        + "\n".join(f"- `{p}`" for p in change_paths)
        + f"\n\n"
        f"**Claude Code version:** `@anthropic-ai/claude-code@{claude_version}`\n\n"
        "**Getting started:**\n"
        "1. Open in GitHub Codespaces or VS Code Dev Containers.\n"
        "2. Set `ANTHROPIC_API_KEY` in Codespaces secrets or local `~/.env`.\n"
        "3. Run `claude` in the terminal.\n\n"
        "**To opt out** per-file: add `AUTO-SYNC-OPT-OUT` anywhere in the target file.\n\n"
        "**To remove this repo from future sweeps:** delete it from the "
        "`matrix.target` list in `.github/workflows/devcontainer-sweep.yml`."
    )
    _run(
        [
            "gh", "pr", "create",
            "--repo", target_repo,
            "--head", branch,
            "--base", "main",
            "--title", f"chore: add dev container with Claude Code @{claude_version}",
            "--body", pr_body,
        ],
        cwd=target_dir,
    )

    print(f"\nOpened PR on {target_repo} from branch {branch}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
