#!/usr/bin/env bash
# ruralpeds org standard dev-container post-create setup.
# Generated by ruralpeds/.github — do not edit manually; changes will be
# overwritten on the next devcontainer-sweep run.
# To opt this file out of future syncs, add: AUTO-SYNC-OPT-OUT anywhere here.
#
# What this does:
#   1. Installs Claude Code CLI (pinned, no known CVEs as of 2026-04-29)
#   2. Installs org-wide Python, Node, Go, Rust, and SBOM tooling
#   3. Installs Julia via the official juliaup apt feed
#   4. Downloads cosign, syft, grype binaries (direct downloads, not curl|bash)
#   5. Downloads FHIR validator JAR

set -euo pipefail

# ── 1. Claude Code CLI ────────────────────────────────────────────────────────
# Pinned to latest version verified clean against GitHub Advisory Database.
# Bump this version only after running: gh-advisory-database check npm @anthropic-ai/claude-code <version>
CLAUDE_CODE_VERSION="2.1.123"
echo "Installing @anthropic-ai/claude-code@${CLAUDE_CODE_VERSION} ..."
npm install -g "@anthropic-ai/claude-code@${CLAUDE_CODE_VERSION}"

# ── 2. Python tooling ─────────────────────────────────────────────────────────
echo "Installing Python tooling ..."
pip install --quiet --upgrade pip
pip install --quiet ruff mypy pre-commit yamllint

# ── 3. Node.js tooling ───────────────────────────────────────────────────────
echo "Installing Node.js tooling ..."
npm install -g prettier@3.3.3 markdownlint-cli@0.42.0 pnpm@9

# ── 4. Go tooling (best-effort) ───────────────────────────────────────────────
if command -v go &>/dev/null; then
  echo "Installing Go tooling ..."
  go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  go install github.com/rhysd/actionlint/cmd/actionlint@latest
fi

# ── 5. Rust tooling (best-effort) ────────────────────────────────────────────
if command -v cargo &>/dev/null; then
  echo "Installing Rust tooling ..."
  cargo install --quiet cargo-deny cargo-audit 2>/dev/null || true
fi

# ── 6. Julia ─────────────────────────────────────────────────────────────────
if ! command -v julia &>/dev/null; then
  echo "Installing Julia via juliaup apt feed ..."
  # Official Julialang apt repository — binary GPG key, not curl|bash.
  wget -qO /tmp/julia-release.gpg \
    https://julialang-s3.julialang.org/juliaup/apt/julia.gpg
  sudo install -D -m 644 /tmp/julia-release.gpg \
    /usr/share/keyrings/julia-release-keyring.gpg
  echo "deb [signed-by=/usr/share/keyrings/julia-release-keyring.gpg] \
https://downloads.julialang.org/juliaup/apt stable main" \
    | sudo tee /etc/apt/sources.list.d/julia.list >/dev/null
  sudo apt-get update -qq
  sudo apt-get install -y --no-install-recommends juliaup
  juliaup add release
  juliaup default release
  rm -f /tmp/julia-release.gpg
fi

# ── 7. SBOM & signing tooling ────────────────────────────────────────────────
# All binaries are downloaded directly from GitHub Releases — no piped shell.
COSIGN_VERSION="v2.4.1"
SYFT_VERSION="1.18.0"
GRYPE_VERSION="0.84.0"

echo "Installing cosign ${COSIGN_VERSION} ..."
curl -sSfL \
  "https://github.com/sigstore/cosign/releases/download/${COSIGN_VERSION}/cosign-linux-amd64" \
  -o /tmp/cosign
chmod +x /tmp/cosign
sudo mv /tmp/cosign /usr/local/bin/cosign

echo "Installing syft ${SYFT_VERSION} ..."
curl -sSfL \
  "https://github.com/anchore/syft/releases/download/v${SYFT_VERSION}/syft_${SYFT_VERSION}_linux_amd64.tar.gz" \
  -o /tmp/syft.tar.gz
tar -xzf /tmp/syft.tar.gz -C /tmp syft
sudo mv /tmp/syft /usr/local/bin/syft
rm -f /tmp/syft.tar.gz

echo "Installing grype ${GRYPE_VERSION} ..."
curl -sSfL \
  "https://github.com/anchore/grype/releases/download/v${GRYPE_VERSION}/grype_${GRYPE_VERSION}_linux_amd64.tar.gz" \
  -o /tmp/grype.tar.gz
tar -xzf /tmp/grype.tar.gz -C /tmp grype
sudo mv /tmp/grype /usr/local/bin/grype
rm -f /tmp/grype.tar.gz

# ── 8. FHIR validator ────────────────────────────────────────────────────────
echo "Installing FHIR validator ..."
sudo apt-get install -y --no-install-recommends default-jre-headless

# Resolve the latest validator_cli.jar URL from the GitHub Releases API,
# then download it without shell execution.
FHIR_JAR_URL=$(curl -sSfL \
  "https://api.github.com/repos/hapifhir/org.hl7.fhir.core/releases/latest" \
  | python3 -c "
import sys, json
data = json.load(sys.stdin)
urls = [a['browser_download_url'] for a in data['assets'] if a['name'] == 'validator_cli.jar']
if not urls:
    raise SystemExit('validator_cli.jar not found in latest HAPI FHIR release')
print(urls[0])
")
curl -sSfL "${FHIR_JAR_URL}" -o /tmp/validator_cli.jar
sudo mv /tmp/validator_cli.jar /usr/local/bin/validator_cli.jar
printf '#!/usr/bin/env bash\nexec java -jar /usr/local/bin/validator_cli.jar "$@"\n' \
  | sudo tee /usr/local/bin/fhir-validator >/dev/null
sudo chmod +x /usr/local/bin/fhir-validator

# ── Done ─────────────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  ruralpeds dev container ready                           ║"
echo "╠══════════════════════════════════════════════════════════╣"
printf "║  claude:  %-46s ║\n" "$(claude --version 2>/dev/null | head -1 || echo 'installed')"
printf "║  python:  %-46s ║\n" "$(python3 --version 2>&1)"
printf "║  node:    %-46s ║\n" "$(node --version)"
printf "║  go:      %-46s ║\n" "$(go version 2>/dev/null | awk '{print $3}' || echo 'not installed')"
printf "║  rust:    %-46s ║\n" "$(rustc --version 2>/dev/null | awk '{print $2}' || echo 'not installed')"
printf "║  julia:   %-46s ║\n" "$(julia --version 2>/dev/null || echo 'not installed')"
echo "╠══════════════════════════════════════════════════════════╣"
echo "║  Set ANTHROPIC_API_KEY in your local .env or shell.      ║"
echo "╚══════════════════════════════════════════════════════════╝"
