#!/usr/bin/env python3
"""
bootstrap_clinical_audit_sweep.py
Rural Peds Clinical Audit Bootstrap Sweep

Sweeps every non-archived Rust and Julia repo in the ruralpeds org and opens
a PR (one per repo) that installs:

  1. .github/workflows/clinical-audit.yml  — calls reusable-clinical-audit.yml
  2. .clinical-audit/.gitkeep              — ensures the audit directory exists
  3. CLAUDE.md snippet                     — if CLAUDE.md exists, appends
                                             clinical audit guidance block

Strategy per repo:
  - Skip if .github/workflows/clinical-audit.yml already exists.
  - Collect files to create/update.
  - Open a single PR on branch bootstrap/clinical-audit-<date>.
  - Never force-push or re-open if a PR for that branch is already open.

Run locally:
  python3 scripts/bootstrap_clinical_audit_sweep.py \\
      --token ghp_... --org ruralpeds

Requires: Python 3.9+, requests (pip install requests)
"""

import argparse
import base64
import json
import sys
import time
from datetime import date
from pathlib import Path

import requests

ORG = "ruralpeds"
TODAY = str(date.today())
BRANCH_NAME = f"bootstrap/clinical-audit-{TODAY}"

REUSABLE_WORKFLOW = "ruralpeds/.github/.github/workflows/reusable-clinical-audit.yml@main"
SCHEMA_URL = "https://github.com/ruralpeds/.github/blob/main/policies/clinical-audit-schema.yaml"

# Repos to unconditionally skip
SKIP_REPOS = {
    ".github",
    "gap-analysis-standard",
    "gap-dashboard",
}

CLINICAL_AUDIT_YML = """\
name: Clinical Function Audit

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  audit:
    uses: ruralpeds/.github/.github/workflows/reusable-clinical-audit.yml@main
    with:
      target_repo: ${{ github.repository }}
      language: auto
      fail_on_flagged: false
      commit_registry: ${{ github.event_name == 'push' }}
    secrets: inherit
"""

GITKEEP_CONTENT = ""

CLAUDE_MD_BLOCK = f"""

---

## Clinical Function Audit

This repo participates in the Rural Peds Clinical Audit system.
Policy & schema: {SCHEMA_URL}

- **Registry:** `.clinical-audit/registry.yaml` — auto-generated by CI on every push.
  Read it to understand which functions have been reviewed and which are pending.
- **Reviewing a function:** run `python3 scripts/clinical_audit_scanner.py review \\
  --repo . --function <name> --status approved --reviewer <your-github-handle>`
  or edit `registry.yaml` manually and set `review.status`, `reviewer`, `reviewed_at`.
- **IEC 62304 class:** set `validation.iec62304_class` (A/B/C) when reviewing.
  Class C functions require unit tests, property tests, and clinician peer review.
- **Flagged functions:** CI does NOT fail on flagged by default. To enforce, set
  `fail_on_flagged: true` in `.github/workflows/clinical-audit.yml`.
- **Stale reviews:** CI emits a warning when `last_modified > last_reviewed`.
  Re-review if the algorithmic change is material.
- **References:** DOI and PMID are extracted automatically from doc comments.
  Add book citations or additional URLs directly in `registry.yaml`.
"""

PR_BODY_TEMPLATE = """\
## Clinical Function Audit — Bootstrap

This PR installs the clinical function audit system for `{repo}`.

### What's included

| File | Purpose |
|------|---------|
| `.github/workflows/clinical-audit.yml` | Calls the org-level reusable audit workflow on push/PR |
| `.clinical-audit/.gitkeep` | Creates the audit directory (scanner writes `registry.yaml` here) |
{claude_md_row}

### How it works

1. On every push to `main` and every PR, `clinical_audit_scanner.py` discovers all
   functions matching clinical criteria (doc comment markers, module path keywords,
   function name patterns).
2. The scanner writes/updates `.clinical-audit/registry.yaml` with git-derived dates,
   extracted references (DOI/PMID), test-file links, and review status.
3. Human reviewers set `review.status = approved | flagged` in the registry.
   Human-owned fields are never overwritten by subsequent scans.

### Next steps after merge

- Review `.clinical-audit/registry.yaml` after the first CI run.
- Set `review.status` for each function (starts as `pending`).
- Assign `validation.iec62304_class` (A/B/C) based on clinical risk.

**Policy & schema:** {schema_url}
"""


def api(method: str, path: str, token: str, **kwargs) -> requests.Response:
    url = f"https://api.github.com{path}"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    r = getattr(requests, method)(url, headers=headers, timeout=30, **kwargs)
    if r.status_code == 403 and "rate limit" in r.text.lower():
        reset = int(r.headers.get("X-RateLimit-Reset", time.time() + 60))
        wait = max(reset - int(time.time()), 5)
        print(f"  ⏳ Rate limited — sleeping {wait}s", flush=True)
        time.sleep(wait)
        r = getattr(requests, method)(url, headers=headers, timeout=30, **kwargs)
    return r


def b64(text: str) -> str:
    return base64.b64encode(text.encode()).decode()


def get_file(org: str, repo: str, path: str, token: str) -> dict | None:
    r = api("get", f"/repos/{org}/{repo}/contents/{path}", token)
    if r.status_code == 404:
        return None
    r.raise_for_status()
    data = r.json()
    content = base64.b64decode(data["content"]).decode("utf-8", errors="replace")
    return {"sha": data["sha"], "content": content}


def create_or_update_file(
    org: str,
    repo: str,
    path: str,
    content: str,
    message: str,
    token: str,
    branch: str,
    sha: str | None = None,
) -> bool:
    payload: dict = {
        "message": message,
        "content": b64(content),
        "branch": branch,
    }
    if sha:
        payload["sha"] = sha
    r = api("put", f"/repos/{org}/{repo}/contents/{path}", token, json=payload)
    if r.status_code in (200, 201):
        return True
    print(f"  ⚠️  PUT {path} → {r.status_code}: {r.text[:200]}")
    return False


def get_default_branch(org: str, repo: str, token: str) -> str:
    r = api("get", f"/repos/{org}/{repo}", token)
    r.raise_for_status()
    return r.json().get("default_branch", "main")


def branch_exists(org: str, repo: str, branch: str, token: str) -> bool:
    r = api("get", f"/repos/{org}/{repo}/git/ref/heads/{branch}", token)
    return r.status_code == 200


def get_branch_sha(org: str, repo: str, branch: str, token: str) -> str:
    r = api("get", f"/repos/{org}/{repo}/git/ref/heads/{branch}", token)
    r.raise_for_status()
    return r.json()["object"]["sha"]


def create_branch(org: str, repo: str, branch: str, from_sha: str, token: str) -> bool:
    r = api("post", f"/repos/{org}/{repo}/git/refs", token, json={
        "ref": f"refs/heads/{branch}",
        "sha": from_sha,
    })
    if r.status_code == 201:
        return True
    print(f"  ⚠️  Create branch → {r.status_code}: {r.text[:200]}")
    return False


def open_pr_exists(org: str, repo: str, branch: str, token: str) -> str | None:
    """Return PR URL if an open PR for this branch already exists, else None."""
    r = api("get", f"/repos/{org}/{repo}/pulls", token,
            params={"state": "open", "head": f"{org}:{branch}", "per_page": 5})
    if r.status_code != 200:
        return None
    prs = r.json()
    return prs[0]["html_url"] if prs else None


def create_pull_request(
    org: str,
    repo: str,
    branch: str,
    default_branch: str,
    token: str,
    has_claude_md: bool,
) -> str | None:
    claude_md_row = (
        "| `CLAUDE.md` (appended) | Adds clinical audit guidance for Claude sessions |"
        if has_claude_md else ""
    )
    body = PR_BODY_TEMPLATE.format(
        repo=f"{org}/{repo}",
        claude_md_row=claude_md_row,
        schema_url=SCHEMA_URL,
    )
    r = api("post", f"/repos/{org}/{repo}/pulls", token, json={
        "title": "chore: install clinical function audit system",
        "body": body,
        "head": branch,
        "base": default_branch,
    })
    if r.status_code == 201:
        return r.json()["html_url"]
    print(f"  ⚠️  PR create → {r.status_code}: {r.text[:300]}")
    return None


def bootstrap_repo(org: str, repo: str, token: str, dry_run: bool) -> dict:
    result = {"repo": repo, "status": "skipped", "actions": [], "pr_url": None}

    # Already installed?
    if get_file(org, repo, ".github/workflows/clinical-audit.yml", token):
        result["status"] = "already_installed"
        return result

    if dry_run:
        result["status"] = "would_install"
        result["actions"] = [
            "create .github/workflows/clinical-audit.yml",
            "create .clinical-audit/.gitkeep",
            "append CLAUDE.md (if present)",
        ]
        return result

    default_branch = get_default_branch(org, repo, token)

    # PR already open?
    existing_pr = open_pr_exists(org, repo, BRANCH_NAME, token)
    if existing_pr:
        result["status"] = "pr_already_open"
        result["pr_url"] = existing_pr
        return result

    # Create branch
    base_sha = get_branch_sha(org, repo, default_branch, token)
    if not create_branch(org, repo, BRANCH_NAME, base_sha, token):
        result["status"] = "error"
        result["errors"] = ["branch creation failed"]
        return result

    errors = []

    # .github/workflows/clinical-audit.yml
    ok = create_or_update_file(
        org, repo, ".github/workflows/clinical-audit.yml",
        content=CLINICAL_AUDIT_YML,
        message="chore: add clinical function audit workflow",
        token=token,
        branch=BRANCH_NAME,
    )
    if ok:
        result["actions"].append("created .github/workflows/clinical-audit.yml")
    else:
        errors.append("clinical-audit.yml create failed")

    # .clinical-audit/.gitkeep
    ok = create_or_update_file(
        org, repo, ".clinical-audit/.gitkeep",
        content=GITKEEP_CONTENT,
        message="chore: create .clinical-audit directory",
        token=token,
        branch=BRANCH_NAME,
    )
    if ok:
        result["actions"].append("created .clinical-audit/.gitkeep")
    else:
        errors.append(".clinical-audit/.gitkeep create failed")

    # CLAUDE.md snippet
    claude_md = get_file(org, repo, "CLAUDE.md", token)
    has_claude_md = claude_md is not None
    if claude_md and "## Clinical Function Audit" not in claude_md["content"]:
        updated = claude_md["content"].rstrip() + CLAUDE_MD_BLOCK
        ok = create_or_update_file(
            org, repo, "CLAUDE.md",
            content=updated,
            message="chore: append clinical audit guidance to CLAUDE.md",
            token=token,
            branch=BRANCH_NAME,
            sha=claude_md["sha"],
        )
        if ok:
            result["actions"].append("updated CLAUDE.md")
        else:
            errors.append("CLAUDE.md update failed")
    elif claude_md and "## Clinical Function Audit" in claude_md["content"]:
        result["actions"].append("CLAUDE.md already has clinical audit block")

    if errors:
        result["status"] = "error"
        result["errors"] = errors
        return result

    # Open PR
    pr_url = create_pull_request(org, repo, BRANCH_NAME, default_branch, token, has_claude_md)
    if pr_url:
        result["status"] = "pr_opened"
        result["pr_url"] = pr_url
    else:
        result["status"] = "error"
        result["errors"] = ["PR creation failed"]

    return result


def list_repos_by_language(org: str, language: str, token: str) -> list[str]:
    """Return list of repo names (not owner/repo) matching the given language."""
    repos = []
    page = 1
    while True:
        r = api("get", f"/orgs/{org}/repos", token,
                params={"per_page": 100, "page": page, "type": "all"})
        r.raise_for_status()
        batch = r.json()
        if not batch:
            break
        for repo in batch:
            if (
                not repo.get("archived", False)
                and (repo.get("language") or "").lower() == language.lower()
            ):
                repos.append(repo["name"])
        page += 1
        if len(batch) < 100:
            break
    return repos


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Bootstrap clinical function audit system across all Rust/Julia repos"
    )
    parser.add_argument("--token", required=True, help="GitHub PAT with repo scope")
    parser.add_argument("--org", default=ORG, help=f"GitHub org (default: {ORG})")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would happen without making changes")
    parser.add_argument("--repo", help="Bootstrap a single named repo only (for testing)")
    parser.add_argument("--skip", nargs="*", default=[],
                        help="Additional repo names to skip")
    args = parser.parse_args()

    skip = SKIP_REPOS | set(args.skip)

    print(f"\n{'DRY RUN — ' if args.dry_run else ''}Clinical Audit Bootstrap Sweep")
    print(f"Org: {args.org}  |  Date: {TODAY}  |  Branch: {BRANCH_NAME}")
    print("─" * 60)

    if args.repo:
        repos_to_process = [args.repo]
    else:
        print("Fetching Rust repos...", flush=True)
        rust_repos = list_repos_by_language(args.org, "Rust", args.token)
        print(f"Fetching Julia repos...", flush=True)
        julia_repos = list_repos_by_language(args.org, "Julia", args.token)
        repos_to_process = sorted(set(rust_repos + julia_repos))
        print(f"Found {len(rust_repos)} Rust + {len(julia_repos)} Julia = "
              f"{len(repos_to_process)} unique repos\n")

    results = []
    for name in repos_to_process:
        if name in skip:
            print(f"  ⏭  {name} — skipped (in skip list)")
            continue

        print(f"  → {name}", end="", flush=True)
        result = bootstrap_repo(args.org, name, args.token, args.dry_run)
        results.append(result)

        status_icon = {
            "pr_opened": "✅",
            "pr_already_open": "🔄",
            "already_installed": "✓",
            "would_install": "📋",
            "error": "❌",
            "skipped": "⏭",
        }.get(result["status"], "?")

        print(f" {status_icon} {result['status']}")
        if result.get("actions"):
            print(f"       {', '.join(result['actions'])}")
        if result.get("pr_url"):
            print(f"       PR: {result['pr_url']}")
        if result.get("errors"):
            for e in result["errors"]:
                print(f"       ⚠️  {e}")

        time.sleep(0.3)

    # ── Summary ───────────────────────────────────────────────────────────────
    print("\n" + "─" * 60)
    opened = [r for r in results if r["status"] == "pr_opened"]
    already_open = [r for r in results if r["status"] == "pr_already_open"]
    already_installed = [r for r in results if r["status"] == "already_installed"]
    would = [r for r in results if r["status"] == "would_install"]
    errors = [r for r in results if r["status"] == "error"]

    if args.dry_run:
        print(f"DRY RUN: {len(would)} would receive PRs, "
              f"{len(already_installed)} already installed")
    else:
        print("Sweep complete:")
        print(f"  ✅ PRs opened:          {len(opened)}")
        print(f"  🔄 PRs already open:    {len(already_open)}")
        print(f"  ✓  Already installed:   {len(already_installed)}")
        print(f"  ❌ Errors:              {len(errors)}")
        if opened or already_open:
            print("\nPRs:")
            for r in opened + already_open:
                print(f"  {r['repo']}: {r['pr_url']}")
        if errors:
            print("\nFailed repos:")
            for r in errors:
                print(f"  {r['repo']}: {r.get('errors', [])}")

    report_path = Path("/tmp/clinical_audit_sweep_report.json")
    report_path.write_text(json.dumps(results, indent=2))
    print(f"\nFull report: {report_path}")

    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
