#!/usr/bin/env python3
"""
container-optimizer.py

Generate optimization suggestions from audit results.
Creates optimized Dockerfile versions with improvements applied.

Usage:
    python3 scripts/container-optimizer.py \
        --audit-file audit-log/container-audit.json \
        --repo-path . \
        --output-dir audit-log/optimization-suggestions

Output:
    - optimization-suggestions.json: Recommendations for each Dockerfile
    - Optimized Dockerfile versions (preview, not committed)
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List


def load_audit_results(audit_file: Path) -> Dict:
    """Load audit results from JSON file."""
    if not audit_file.exists():
        print(f"⚠️  Audit file not found: {audit_file}")
        return {}

    try:
        with open(audit_file) as f:
            return json.load(f)
    except Exception as e:
        print(f"⚠️  Error loading audit: {e}")
        return {}


def generate_suggestions_for_dockerfile(dockerfile_result: Dict) -> Dict:
    """Generate specific optimization suggestions for a Dockerfile."""
    suggestions = {
        "path": dockerfile_result.get("path"),
        "base_image": dockerfile_result.get("base_image"),
        "issue_count": len(dockerfile_result.get("issues", [])),
        "suggestions": []
    }

    for issue in dockerfile_result.get("issues", []):
        issue_type = issue.get("type")

        if issue_type == "non-slim-base-image":
            suggestions["suggestions"].append({
                "type": "base_image_optimization",
                "priority": "high",
                "current": issue.get("current"),
                "suggested": issue.get("suggested"),
                "savings": {
                    "size_reduction_percent": issue.get("size_savings_percent"),
                    "risk_level": issue.get("risk_level")
                },
                "implementation": f"Change FROM {issue.get('current')} to FROM {issue.get('suggested')}",
                "testing": "Full test suite should pass with new base image",
                "estimated_build_time_impact": "+1-2 minutes (new base image pull)"
            })

        elif issue_type == "missing-multi-stage":
            suggestions["suggestions"].append({
                "type": "multi_stage_build",
                "priority": "high",
                "savings": {
                    "size_reduction_percent": issue.get("size_savings_percent"),
                    "build_time_reduction_percent": issue.get("build_time_savings_percent")
                },
                "implementation": """
                1. Add AS builder to first FROM
                2. Create second FROM with runtime base image
                3. COPY --from=builder to import only production files
                4. Remove build tools from final image
                """,
                "testing": "Verify runtime dependencies available in final image",
                "estimated_risk": "medium"
            })

        elif issue_type == "layer-cache-miss":
            suggestions["suggestions"].append({
                "type": "layer_caching_optimization",
                "priority": "high",
                "savings": {
                    "build_time_reduction_percent": issue.get("build_time_impact_percent")
                },
                "implementation": issue.get("fix"),
                "explanation": "By copying only dependencies before copying all source, Docker can cache the dependency installation layer and reuse it on subsequent builds when only source code changes",
                "testing": "Verify subsequent builds after source change hit cache on dependency layer"
            })

    return suggestions


def create_optimized_dockerfile_template(base_suggestion: Dict) -> str:
    """Create an optimized Dockerfile template."""
    template = "# Optimized Dockerfile (generated by container-optimizer.py)\n"
    template += "# Review changes carefully before applying\n\n"

    base_image = base_suggestion.get("base_image", "ubuntu:20.04")
    suggestions = base_suggestion.get("suggestions", [])

    # Check if multi-stage suggested
    has_multi_stage = any(s["type"] == "multi_stage_build" for s in suggestions)

    if has_multi_stage:
        template += "# Multi-stage build recommended\n"
        template += "FROM node:16 AS builder\n"
        template += "WORKDIR /app\n"
        template += "COPY package*.json ./\n"
        template += "RUN npm ci\n"
        template += "COPY . .\n"
        template += "RUN npm run build\n\n"

        template += "# Runtime stage\n"
        suggested_base = next((s["suggested"] for s in suggestions if s["type"] == "base_image_optimization"), None)
        if suggested_base:
            template += f"FROM {suggested_base}\n"
        else:
            template += "FROM node:16-alpine\n"

        template += "WORKDIR /app\n"
        template += "COPY --from=builder /app/dist ./dist\n"
        template += "COPY --from=builder /app/node_modules ./node_modules\n"
        template += "CMD [\"node\", \"dist/server.js\"]\n"
    else:
        template += "# Optimize base image\n"
        suggested_base = next((s["suggested"] for s in suggestions if s["type"] == "base_image_optimization"), None)
        if suggested_base:
            template += f"FROM {suggested_base}\n"
        else:
            template += "FROM ubuntu:20.04\n"

        template += "# ... rest of Dockerfile with optimization comments\n"

    return template


def main():
    parser = argparse.ArgumentParser(description="Generate optimization suggestions from audit results")
    parser.add_argument(
        "--audit-file",
        type=Path,
        default=Path("audit-log/container-audit.json"),
        help="Audit results JSON file"
    )
    parser.add_argument(
        "--repo-path",
        type=Path,
        default=Path("."),
        help="Repository root path"
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("audit-log/optimization-suggestions"),
        help="Output directory for suggestions"
    )
    args = parser.parse_args()

    print(f"\n🔧 Container Optimizer\n")
    print(f"Audit file: {args.audit_file}")
    print(f"Output directory: {args.output_dir}")

    # Load audit results
    print(f"\nLoading audit results...", end=" ", flush=True)
    audit_report = load_audit_results(args.audit_file)
    if not audit_report:
        print(f"✗ No audit results")
        return 1
    print(f"✓ Loaded")

    # Generate suggestions
    print(f"Generating optimization suggestions...", end=" ", flush=True)

    dockerfiles = audit_report.get("dockerfiles", [])
    suggestions_list = []

    for dockerfile in dockerfiles:
        suggestion = generate_suggestions_for_dockerfile(dockerfile)
        suggestions_list.append(suggestion)

    print(f"✓ Generated {len(suggestions_list)} suggestions")

    # Create output directory
    args.output_dir.mkdir(parents=True, exist_ok=True)

    # Write suggestions
    print(f"Writing suggestions...", end=" ", flush=True)

    suggestions_file = args.output_dir / "optimization-suggestions.json"
    with open(suggestions_file, "w") as f:
        json.dump({
            "timestamp": __import__("datetime").datetime.utcnow().isoformat(),
            "total_dockerfiles": len(dockerfiles),
            "dockerfiles_with_suggestions": sum(1 for s in suggestions_list if s["suggestions"]),
            "total_suggestions": sum(len(s["suggestions"]) for s in suggestions_list),
            "suggestions": sorted(
                suggestions_list,
                key=lambda x: x["issue_count"],
                reverse=True
            )
        }, f, indent=2)

    print(f"✓ Complete")

    # Create sample optimized Dockerfiles
    print(f"Creating sample Dockerfiles...", end=" ", flush=True)

    sample_dir = args.output_dir / "samples"
    sample_dir.mkdir(exist_ok=True)

    for suggestion in suggestions_list[:3]:  # Create samples for top 3
        if suggestion["suggestions"]:
            template = create_optimized_dockerfile_template(suggestion)
            sample_file = sample_dir / f"{Path(suggestion['path']).stem}-optimized.Dockerfile"

            with open(sample_file, "w") as f:
                f.write(template)

    print(f"✓ Created {min(3, sum(1 for s in suggestions_list if s['suggestions']))} samples")

    # Print summary
    print(f"\n{'='*70}")
    print("OPTIMIZATION SUMMARY")
    print(f"{'='*70}\n")

    total_suggestions = sum(len(s["suggestions"]) for s in suggestions_list)
    print(f"Dockerfiles analyzed: {len(dockerfiles)}")
    print(f"Dockerfiles with suggestions: {sum(1 for s in suggestions_list if s['suggestions'])}")
    print(f"Total suggestions: {total_suggestions}")

    print(f"\nTop optimization opportunities:")
    for i, suggestion in enumerate(sorted(suggestions_list, key=lambda x: len(x["suggestions"]), reverse=True)[:5], 1):
        if suggestion["suggestions"]:
            print(f"  {i}. {suggestion['path']}: {len(suggestion['suggestions'])} suggestions")

    print(f"\nSuggestion breakdown:")
    base_image_count = sum(
        1 for s in suggestions_list
        for sugg in s["suggestions"]
        if sugg["type"] == "base_image_optimization"
    )
    multi_stage_count = sum(
        1 for s in suggestions_list
        for sugg in s["suggestions"]
        if sugg["type"] == "multi_stage_build"
    )
    caching_count = sum(
        1 for s in suggestions_list
        for sugg in s["suggestions"]
        if sugg["type"] == "layer_caching_optimization"
    )

    print(f"  Base image optimization: {base_image_count}")
    print(f"  Multi-stage build: {multi_stage_count}")
    print(f"  Layer caching: {caching_count}")

    print(f"\n📄 Suggestions: {suggestions_file}")
    print(f"📄 Sample optimized Dockerfiles: {sample_dir}/")

    return 0 if total_suggestions == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
