#!/usr/bin/env python3
"""
stale_sweeper.py — find org repos whose AUDIT.yaml is stale and open issues.

Reads env:
  ORG           — org login
  STALE_DAYS    — threshold to consider stale
  OVERDUE_DAYS  — threshold to consider overdue (escalates issue priority)
  DRY_RUN       — "true" to skip issue creation
  GH_TOKEN      — provided by Actions

Logic per repo:
  • Fetch .github/AUDIT.yaml (skip repos without one — those get a separate
    "missing audit" sweep that is less aggressive, once per quarter).
  • Compute age since last_reviewed.
  • If age > stale_days, check for an open issue with label `audit-stale`.
    - If one exists: update its body with current age, no spam comment unless
      now overdue.
    - If none: open one. Assign to reviewer if listed in AUDIT metadata.
  • Post summary comment to ruralpeds/.github issue #1 (create if missing).
"""

from __future__ import annotations

import base64
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from typing import Any

from dateutil.parser import parse as parse_dt
import yaml


def gh(path: str, *, method: str = "GET", body: Any = None,
       jq: str | None = None, allow_404: bool = True) -> Any:
    cmd = ["gh", "api", "-H", "Accept: application/vnd.github+json",
           "-X", method, path]
    if body is not None:
        cmd += ["--input", "-"]
    if jq:
        cmd += ["--jq", jq]
    try:
        out = subprocess.check_output(
            cmd, text=True, stderr=subprocess.PIPE,
            input=json.dumps(body) if body else None,
        )
    except subprocess.CalledProcessError as e:
        if allow_404 and "404" in (e.stderr or ""):
            return None
        print(f"WARN {path}: {e.stderr.strip()}", file=sys.stderr)
        return None
    return json.loads(out) if out.strip() else None


def gh_paginate(path: str) -> list:
    out: list = []
    page = 1
    while True:
        sep = "&" if "?" in path else "?"
        chunk = gh(f"{path}{sep}per_page=100&page={page}")
        if not chunk:
            break
        out.extend(chunk)
        if len(chunk) < 100:
            break
        page += 1
    return out


def load_audit(org: str, repo: str) -> dict | None:
    for name in (".github/AUDIT.yaml", ".github/AUDIT.yml"):
        data = gh(f"repos/{org}/{repo}/contents/{name}")
        if data and data.get("type") == "file":
            try:
                return yaml.safe_load(base64.b64decode(data["content"]).decode())
            except Exception:
                return None
    return None


def ensure_label(org: str, repo: str, label: str, color: str, desc: str) -> None:
    existing = gh(f"repos/{org}/{repo}/labels/{label}")
    if existing:
        return
    gh(f"repos/{org}/{repo}/labels", method="POST",
       body={"name": label, "color": color, "description": desc})


def existing_stale_issue(org: str, repo: str) -> dict | None:
    issues = gh(f"repos/{org}/{repo}/issues?state=open&labels=audit-stale&per_page=10")
    return issues[0] if issues else None


ISSUE_BODY = """### Audit review overdue

The automated sweeper found this repository's `.github/AUDIT.yaml` has not
been reviewed in **{age} days** (threshold: {threshold} days).

- **Classification:** `{classification}`
- **Last reviewed:** {last_reviewed}
- **Reviewer:** {reviewer}
- **FDA class:** {fda_class}

### To resolve

Run the audit workflow with `mark-reviewed: true`:

```bash
gh workflow run audit.yml -R {org}/{repo} -f mark-reviewed=true -f reviewer=@me
```

Or approve via the **Actions** tab → **Audit Log** → **Run workflow**
→ check *"Mark this repo as reviewed today"*.

For clinical-software and FDA Class II/III repos, this review is not
optional — it's a documented quality-system requirement.

---

*Auto-generated by stale-repo-sweeper. Do not delete this issue; it will
be updated in place on each sweep until resolved.*
"""


def open_or_update_issue(org: str, repo: str, entry: dict, dry_run: bool) -> str:
    existing = existing_stale_issue(org, repo)
    age      = entry["age_days"]
    overdue  = entry["state"] == "overdue"
    body     = ISSUE_BODY.format(
        age=age, threshold=entry["threshold"],
        classification=entry["classification"],
        last_reviewed=entry["last_reviewed"],
        reviewer=entry["reviewer"] or "(none listed)",
        fda_class=entry["fda_class"] or "none",
        org=org, repo=repo,
    )
    priority_label = "priority-high" if overdue else "priority-normal"

    if dry_run:
        return f"WOULD {'update' if existing else 'open'} issue"

    ensure_label(org, repo, "audit-stale", "FBCA04",
                 "AUDIT.yaml not reviewed recently")
    ensure_label(org, repo, priority_label,
                 "B60205" if overdue else "0E8A16",
                 "sweeper priority")

    if existing:
        gh(f"repos/{org}/{repo}/issues/{existing['number']}", method="PATCH",
           body={"body": body,
                 "labels": ["audit-stale", priority_label]})
        if overdue and "audit-stale" not in {l["name"] for l in existing.get("labels", [])}:
            gh(f"repos/{org}/{repo}/issues/{existing['number']}/comments",
               method="POST",
               body={"body": f"⚠ Escalating: now {age} days stale (overdue threshold {entry['overdue_threshold']})."})
        return f"updated #{existing['number']}"

    title = f"Audit review overdue ({age}d)"
    assignees = [entry["reviewer"]] if entry["reviewer"] and not entry["reviewer"].startswith("audit-") else []
    new = gh(f"repos/{org}/{repo}/issues", method="POST",
             body={"title": title, "body": body,
                   "labels": ["audit-stale", priority_label],
                   "assignees": assignees})
    return f"opened #{new['number']}" if new else "open failed"


def main() -> int:
    org          = os.environ["ORG"]
    stale_days   = int(os.environ.get("STALE_DAYS", 180))
    overdue_days = int(os.environ.get("OVERDUE_DAYS", 365))
    dry_run      = os.environ.get("DRY_RUN", "false").lower() == "true"

    print(f"▶ Sweeping {org} (stale >{stale_days}d, overdue >{overdue_days}d, dry_run={dry_run})",
          file=sys.stderr)

    repos = gh_paginate(f"orgs/{org}/repos?type=all")
    active = [r for r in repos if not r.get("archived")]

    report = []
    for r in active:
        name = r["name"]
        audit = load_audit(org, name)
        if not audit:
            report.append({"repo": name, "state": "no-audit"})
            continue
        meta = audit.get("metadata", {}) or {}
        last = meta.get("last_reviewed")
        if not last:
            report.append({"repo": name, "state": "no-review-date"})
            continue
        age = (datetime.now(timezone.utc) - parse_dt(last)).days
        state = ("overdue" if age > overdue_days else
                 "stale"   if age > stale_days   else "fresh")
        entry = {
            "repo":          name,
            "state":         state,
            "age_days":      age,
            "threshold":     stale_days,
            "overdue_threshold": overdue_days,
            "last_reviewed": last,
            "classification": meta.get("classification", "unknown"),
            "reviewer":      meta.get("reviewer"),
            "fda_class":     audit.get("compliance", {}).get("fda_class"),
        }
        if state in ("stale", "overdue"):
            entry["action"] = open_or_update_issue(org, name, entry, dry_run)
        report.append(entry)

    # summary
    totals = {"fresh": 0, "stale": 0, "overdue": 0,
              "no-audit": 0, "no-review-date": 0}
    for e in report:
        totals[e["state"]] = totals.get(e["state"], 0) + 1

    print("\n=== Sweep Summary ===")
    for s, n in totals.items():
        print(f"  {s:<15}  {n}")

    summary_path = "$GITHUB_STEP_SUMMARY"
    gh_step = os.environ.get("GITHUB_STEP_SUMMARY")
    if gh_step:
        with open(gh_step, "a") as f:
            f.write("## Stale Repo Sweep\n\n")
            f.write("| State | Count |\n|---|---|\n")
            for s, n in totals.items():
                f.write(f"| {s} | {n} |\n")
            f.write("\n### Details\n\n")
            f.write("| Repo | State | Age | Action |\n|---|---|---|---|\n")
            for e in report:
                if e["state"] in ("stale", "overdue"):
                    f.write(f"| {e['repo']} | {e['state']} | "
                            f"{e.get('age_days','?')}d | "
                            f"{e.get('action','')} |\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
